spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/raptor_intelligence
    username: raptor
    password: raptor123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: sua-chave-secreta-256bits-aqui-trocar-em-producao
  expiration: 86400000
